name: Secrets Scan

on:
  push:
    branches:
      - "master"

jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Install git-secrets
      run: |
        wget https://github.com/awslabs/git-secrets/archive/refs/tags/1.3.0.tar.gz
        tar -xvf 1.3.0.tar.gz
        sudo apt-get install build-essential
        cd git-secrets-1.3.0
        sudo make install

    - name: Scan for Secrets
      run: git secrets --scan
